"""empty message

Revision ID: 4a4f001ae5a9
Revises: 
Create Date: 2020-02-07 23:34:22.450795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4f001ae5a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('game_title', sa.String(length=80), nullable=False),
    sa.Column('game_plataform', sa.String(length=80), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('entrance_fee', sa.String(length=120), nullable=False),
    sa.Column('prize', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('organizator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_inscription', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('competitor_one_id', sa.Integer(), nullable=True),
    sa.Column('competitor_two_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_result_one', sa.Integer(), nullable=False),
    sa.Column('match_result_two', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_one_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['competitor_two_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_match')
    op.drop_table('inscription')
    op.drop_table('tournament')
    op.drop_table('user')
    # ### end Alembic commands ###
