"""empty message

Revision ID: 621df00d334b
Revises: 461cb991569e
Create Date: 2020-02-14 21:38:11.419374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621df00d334b'
down_revision = '461cb991569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('matches_created', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'matches_created')
    # ### end Alembic commands ###
