"""empty message

Revision ID: 7dc2c1e4d476
Revises: 6fe91bfc911e
Create Date: 2020-02-05 23:39:37.252772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dc2c1e4d476'
down_revision = '6fe91bfc911e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('competitor_one_id', sa.Integer(), nullable=True),
    sa.Column('competitor_two_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_result_one', sa.Integer(), nullable=False),
    sa.Column('match_result_two', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_one_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['competitor_two_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tournament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('competitor_one_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('competitor_two_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('match_result_one', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('match_result_two', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('round', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competitor_one_id'], ['user.id'], name='match_ibfk_1'),
    sa.ForeignKeyConstraint(['competitor_two_id'], ['user.id'], name='match_ibfk_2'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='match_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('tournament_match')
    # ### end Alembic commands ###
